<a href="https://colab.research.google.com/github/ademaratioluwatoyin/HAMOYE-STAGE-A/blob/main/HAMOYE_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **HAMOYE STAGE A PROJECT**



In [1]:
#import necessary libraries

import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns

QUESTION 1

In [2]:
A = [1,2,3,4,5,6]
B =  [13,21,34]
A.extend(B)
A

[1, 2, 3, 4, 5, 6, 13, 21, 34]

QUESTION 2

In [3]:
# an identity matrix can be created using the numpy function 'identity'
# i.e
matrix_A = np.identity(3)
matrix_A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
# or by writing out each element like this
matrix_B = np.array([[1,0,0],[0,1,0],[0,0,1]])
matrix_B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
# or by using the numpy function 'eye'
matrix_C = np.eye(3)
matrix_C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

THE DATASET

In [6]:
# load data with pandas into a fuel_data
fuel_data = pd.read_csv('https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv')

# display the first 5 rows of dataset
fuel_data.head()

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [7]:
# print number of rows and number of columns
print('number of rows =', len(fuel_data.index))
print('number of columns =', len(fuel_data.columns))

number of rows = 29523
number of columns = 11


In [ ]:
fuel_data.describe(include = 'all')

record_id  ...  fuel_cost_per_mmbtu
count                     29523  ...         29523.000000
unique                    29523  ...                  NaN
top     f1_fuel_2008_12_145_1_3  ...                  NaN
freq                          1  ...                  NaN
mean                        NaN  ...            19.304354
std                         NaN  ...          2091.540939
min                         NaN  ...           -41.501000
25%                         NaN  ...             1.940000
50%                         NaN  ...             4.127000
75%                         NaN  ...             7.745000
max                         NaN  ...        359278.000000

[11 rows x 11 columns]

QUESTION 3

In [8]:
# displaying all fuel types and their average fuel cost per unit burned in ascending order
fuel_data[['fuel_type_code_pudl','fuel_cost_per_unit_burned']].groupby('fuel_type_code_pudl').mean().sort_values(ascending = True, by = 'fuel_cost_per_unit_burned')

fuel_cost_per_unit_burned
fuel_type_code_pudl                           
gas                                  13.659397
other                                18.253856
waste                                19.518122
coal                                 67.421830
oil                                 168.877086
nuclear                            4955.157002

In [9]:
# the lowest from the above is gas with an average of 13.66 in 2dp

# writing a program to print the lowest

# get all fuel types and average fuel cost per unit burned
average_fuel_cost_by_fuel_type = fuel_data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()
# use a for loop and if statement to print the lowest 
for i in average_fuel_cost_by_fuel_type:
  if i == average_fuel_cost_by_fuel_type.min():
    print('The lowest is',average_fuel_cost_by_fuel_type[average_fuel_cost_by_fuel_type == i].index[0],'with an average of',i)

The lowest is gas with an average of 13.659396569737135


QUESTION 4

In [10]:
# standard deviation of measure of enery per unit
std = round(fuel_data['fuel_mmbtu_per_unit'].std(),2)

# 75th percentile
percentile = round(fuel_data['fuel_mmbtu_per_unit'].quantile(0.75),2)

print('Standard Deviation =',std,'\n75th Percentile =',percentile)

Standard Deviation = 10.6 
75th Percentile = 17.01


QUESTION 5

In [11]:
# skewness for the fuel quantity burned in two decimal places
skewness = round(fuel_data['fuel_qty_burned'].skew(),2)

#kurtosis for the fuel quantity burned
kurtosis = round(fuel_data['fuel_qty_burned'].kurtosis(),2)

print('Skewness =', skewness,'\nKurtosis =', kurtosis)

Skewness = 15.85 
Kurtosis = 651.37


QUESTION 6

In [12]:
# checking for all rows and number of missing value 
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [13]:
# You can simply print only rows with missing values
missing = fuel_data.isnull().sum()
for i in missing:
  if i > 1:
    print('Missing row is',missing[missing == i].index[0],'\nNumber of missing values =',i)
    # display percent of missing rows
    print('Percent missing =', round(i/len(fuel_data.index)*100,2),'%')

Missing row is fuel_unit 
Number of missing values = 180
Percent missing = 0.61 %


QUESTION 7

In [14]:
# display all unique values of fuel_unit
fuel_data['fuel_unit'].unique()

array(['ton', 'mcf', 'kgU', 'bbl', 'gramsU', nan, 'mwdth', 'mmbtu',
       'mwhth', 'gal'], dtype=object)

Values are **categorical** and **mode imputation** technique should be used 

QUESTION 8

In [15]:
fuel_data.corr()['fuel_cost_per_unit_burned'].sort_values(ascending = True)

utility_id_ferc1               -0.037863
fuel_qty_burned                -0.018535
fuel_mmbtu_per_unit            -0.010034
fuel_cost_per_mmbtu            -0.000437
fuel_cost_per_unit_delivered    0.011007
report_year                     0.013599
fuel_cost_per_unit_burned       1.000000
Name: fuel_cost_per_unit_burned, dtype: float64

The second and third lowest correlation are *fuel_qty_burned* and *fuel_mmbtu_per_unit* respectively 

QUESTION 9

In [16]:
#For the fuel type coal, what is the percentage change in the fuel cost per unit burned in 1998 compared to 1994?
a = fuel_data[['report_year','fuel_type_code_pudl','fuel_cost_per_unit_burned']].groupby('report_year').get_group(1994)
b = fuel_data[['report_year','fuel_type_code_pudl','fuel_cost_per_unit_burned']].groupby('report_year').get_group(1998)
coal_sum_94 = a[['fuel_type_code_pudl','fuel_cost_per_unit_burned']].groupby('fuel_type_code_pudl').sum().loc['coal','fuel_cost_per_unit_burned']
coal_sum_98 = b[['fuel_type_code_pudl','fuel_cost_per_unit_burned']].groupby('fuel_type_code_pudl').sum().loc['coal', 'fuel_cost_per_unit_burned']
percent_change = (coal_sum_98-coal_sum_94)/coal_sum_94*100
print('Percent change =',round(percent_change),'%')

Percent change = -21 %


QUESTION 10

In [17]:
# display report year and average fuel cost per unit delivered in dataframe
fuel_data[['report_year', 'fuel_cost_per_unit_delivered']].groupby('report_year').mean().sort_values(ascending = False, by ='fuel_cost_per_unit_delivered')

fuel_cost_per_unit_delivered
report_year                              
1997                         11140.197239
1996                          9196.705948
2000                           985.362877
2009                           652.694163
2018                           499.269966
2015                           326.535511
1998                           287.154420
2014                           192.737183
2013                           172.307591
2004                           139.524275
2016                           103.901761
2010                            91.862105
1994                            63.636060
2012                            60.994502
2001                            60.050396
2011                            59.774667
2008                            58.588197
2003                            55.663493
2002                            47.594361
2017                            46.196861
2007                            43.325023
2005                            41.438184
2006                            38.657484
1995                            32.735269
1999                            25.551627

Highest is 1997

In [32]:
# write a program to print the year
c = fuel_data[['report_year', 'fuel_cost_per_unit_delivered']].groupby('report_year').mean()
print('Year =', c.idxmax())

Year = fuel_cost_per_unit_delivered    1997
dtype: int64
